[package]
name = "land_nft"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.10.2"
ic-cdk-macros = "0.8.0"
candid = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
